export const httpErrors: Record<number, string> = {
	// 4xx - Erreurs client
	400: 'La requête est invalide ou mal formulée.',
	401: 'Authentification requise pour accéder à cette ressource.',
	402: 'Paiement requis.',
	403: "Accès refusé. Vous n'avez pas les permissions nécessaires.",
	404: 'La page demandée est introuvable.',
	405: 'Méthode HTTP non autorisée pour cette ressource.',
	406: "Le contenu demandé n'est pas acceptable.",
	407: 'Authentification requise auprès du proxy.',
	408: 'Le serveur a expiré en attendant la requête.',
	409: "Conflit avec l'état actuel de la ressource.",
	410: 'Cette ressource a été définitivement supprimée.',
	411: 'La longueur du contenu doit être spécifiée.',
	412: "Une condition préalable de la requête n'a pas été satisfaite.",
	413: 'La requête est trop volumineuse pour être traitée.',
	414: "L'URL fournie est trop longue.",
	415: "Le type de média n'est pas pris en charge.",
	416: "La plage demandée n'est pas disponible.",
	417: "L'attente indiquée dans l'en-tête n'a pas pu être satisfaite.",
	418: 'Je suis une théière. ☕',
	421: "La requête a été envoyée à un serveur incapable d'y répondre.",
	422: 'La requête est correcte mais impossible à traiter.',
	423: 'La ressource est verrouillée.',
	424: "La requête a échoué car elle dépend d'une autre requête qui a échoué.",
	425: 'Le serveur refuse de traiter une requête qui pourrait être rejouée.',
	426: 'Une mise à jour du protocole est nécessaire.',
	428: 'Une condition préalable est requise pour cette requête.',
	429: 'Trop de requêtes envoyées. Veuillez réessayer plus tard.',
	431: 'Les en-têtes de la requête sont trop volumineux.',
	451: 'Ressource indisponible pour des raisons légales.',

	// 5xx - Erreurs serveur
	500: 'Erreur interne du serveur.',
	501: 'Fonctionnalité non implémentée par le serveur.',
	502: 'Réponse invalide reçue depuis le serveur en amont.',
	503: 'Service temporairement indisponible.',
	504: "Le serveur en amont n'a pas répondu à temps.",
	505: 'Version HTTP non prise en charge.',
	506: 'Erreur de négociation de contenu.',
	507: 'Espace de stockage insuffisant sur le serveur.',
	508: 'Boucle infinie détectée lors du traitement.',
	510: 'Des extensions supplémentaires sont nécessaires.',
	511: 'Authentification réseau requise.'
};
